language: java

jdk:
  - oraclejdk8

cache:
  directories:
  - $HOME/.m2
  
install:
  - mvn --settings .travis/settings.xml install -DskipTests=true -Dmaven.javadoc.skip=true -B -V

before_install:
  - echo $GPG_SECRET_KEYS | base64 --decode | $GPG_EXECUTABLE --import
  - echo $GPG_OWNERTRUST | base64 --decode | $GPG_EXECUTABLE --import-ownertrust

notifications:
    slack: openbase-org:$SLACK_ACCESS_TOCKEN
    on_failure: change
    on_success: change	

deploy:
  - provider: script
    script: .travis/deploy.sh
    on:
        repo: openbase/generic-display
        branch: master
        jdk: oraclejdk8
  - provider: script
    script: .travis/deploy.sh
    on:
        repo: openbase/generic-display
        tags: true
        jdk: oraclejdk8
